const BAD_REQUEST_STATUS_CODE = 400;
const RESOURCE_NOT_FOUND = 404;
const DEFAULT_SERVER_ERROR = 500;
const FORBIDDEN = 403;
const CONFLICT = 409;
const UNAUTHORIZED = 401;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  RESOURCE_NOT_FOUND,
  DEFAULT_SERVER_ERROR,
  FORBIDDEN,
  CONFLICT,
  UNAUTHORIZED,
};
